# Generated by Django 3.1.7 on 2021-03-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('nbQuestionsByMonth', models.IntegerField()),
            ],
            options={
                'db_table': 'app_questionsummary',
                'managed': False,
            },
        ),
    ]
