# Generated by Django 3.1.7 on 2021-03-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_questionsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionSummary',
        ),
        migrations.CreateModel(
            name='AuthorClone',
            fields=[
            ],
            options={
                'verbose_name_plural': 'The Authors clone',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sample_app.author',),
        ),
    ]
